Another Windows compile fix. I think these have all come up because boost has updated to a new version that is incompatible with the C++ compiler used to build conda on windows...
I have had to disable findMCS on Windows because boost/graph/mcgregor_common_subgraphs.hpp
won't compile because it pulls in boost/describe.hpp which fails its compile with the error
message

C:\Users\chris\miniforge3\envs\openbiosim\Library\include\boost/describe/enumerators.hpp(22): error C2065: 'boost_enum_descriptor_fn': undeclared iden
tifier [C:\Users\chris\Coding\sire\build\openbiosim_openbiosim_corelib\src\libs\SireMol\SireMol.vcxproj]

(amongst others)

I'll try the CI again...